Initial refactor based on hoodie-store.
hoodiehq/hoodie-task pull request #3
Opened 2017-01-17 01:49 UTC by inator

@gr2m - ready for your initial review! :)

2017-01-17 02:05 UTC, gr2m requested changes
I would remove the tests entirely, including all the packages that we only need for testing. We no longer use `@gr2m/frontend-test-setup`, instead we use [selsa](https://www.npmjs.com/package/selsa). I can help setting it up in a follow up PR, you can have a glance at https://github.com/hoodiehq/hoodie-app-tracker/tree/master/test

We also no longer load `"pouchdb"` directly, instead we use [custom builds](https://pouchdb.com/custom.html). So here in our case I think we need `pouchdb-core` and `pouchdb-adapter-memory`, maybe `pouchdb-mapreduce` and `pouchdb-replication`.

Does that all make sense?

2017-01-17 02:05 UTC, gr2m commented on example/index.js
> +var hapiStore = require('../server')
rename to `hapiTask`

2017-01-17 02:15 UTC, gr2m commented on .gitignore
> -.db
keep the `.db` in here, it is where PouchDB writes its files into. Unless we decide to use `pouchdb-adapter-memory` only

2017-01-29 07:16 UTC, gr2m commented
@inator is the review clear? Anything I can help with?

2017-01-31 17:16 UTC, inator commented
> @inator is the review clear? Anything I can help with?

@gr2m - Sorry for the delay.  I hope to dive back in this week.

2017-02-03 17:17 UTC, inator commented
> We also no longer load "pouchdb" directly, instead we use custom builds. So here in our case I think we need pouchdb-core and pouchdb-adapter-memory, maybe pouchdb-mapreduce and pouchdb-replication.

@gr2m - I'm finally getting back to this.  I based this on [this](https://github.com/hoodiehq/hoodie-store/blob/master/example/index.js#L2).  Do you have an example you can point me to where you do this?

2017-02-03 17:25 UTC, gr2m commented
`hoodie-store` is a bit outdated, we don’t use it in our architecture anymore. Here is where we load PouchDB in `hoodie`: https://github.com/hoodiehq/hoodie/blob/master/cli/parse-options.js#L5

2017-02-03 18:02 UTC, inator commented
@gr2m - I think I addressed all the immediate changes requested.  Hopefully this will get us started with some local testing of tasks. :)

2017-02-03 19:27 UTC, gr2m approved these changes
great start!

2017-02-03 19:28 UTC, merged